# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 测试zlzq

on:
  workflow_dispatch:
  schedule:
     - cron: '0 */1 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      CommonHeaders: ${{ secrets.COMMONHEADERS }}
      CommonTokens: ${{ secrets.COMMONTOKENS }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行zlzq'
        if: env.CommonHeaders
        run: |
          node zhuanq.js
        env:
          CommonHeaders: ${{ secrets.COMMONHEADERS }}
          CommonTokens: ${{ secrets.COMMONTOKENS }}
